<?php

/**
 * BaseTeamUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $team_id
 * @property integer $user_id
 * @property Team $Team
 * @property sfGuardUser $sfGuardUser
 * 
 * @method integer     getTeamId()      Returns the current record's "team_id" value
 * @method integer     getUserId()      Returns the current record's "user_id" value
 * @method Team        getTeam()        Returns the current record's "Team" value
 * @method sfGuardUser getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method TeamUser    setTeamId()      Sets the current record's "team_id" value
 * @method TeamUser    setUserId()      Sets the current record's "user_id" value
 * @method TeamUser    setTeam()        Sets the current record's "Team" value
 * @method TeamUser    setSfGuardUser() Sets the current record's "sfGuardUser" value
 * 
 * @package    futebol
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTeamUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('team_user');
        $this->hasColumn('team_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Team', array(
             'local' => 'team_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));
    }
}