<?php

/**
 * BaseTeamAsset
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $team_id
 * @property integer $asset_id
 * @property boolean $is_active
 * @property integer $display_order
 * @property Team $Team
 * @property Asset $Asset
 * 
 * @method integer   getTeamId()        Returns the current record's "team_id" value
 * @method integer   getAssetId()       Returns the current record's "asset_id" value
 * @method boolean   getIsActive()      Returns the current record's "is_active" value
 * @method integer   getDisplayOrder()  Returns the current record's "display_order" value
 * @method Team      getTeam()          Returns the current record's "Team" value
 * @method Asset     getAsset()         Returns the current record's "Asset" value
 * @method TeamAsset setTeamId()        Sets the current record's "team_id" value
 * @method TeamAsset setAssetId()       Sets the current record's "asset_id" value
 * @method TeamAsset setIsActive()      Sets the current record's "is_active" value
 * @method TeamAsset setDisplayOrder()  Sets the current record's "display_order" value
 * @method TeamAsset setTeam()          Sets the current record's "Team" value
 * @method TeamAsset setAsset()         Sets the current record's "Asset" value
 * 
 * @package    futebol
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTeamAsset extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('team_asset');
        $this->hasColumn('team_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('asset_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('display_order', 'integer', null, array(
             'type' => 'integer',
             ));


        $this->index('is_active_idx', array(
             'fields' => 
             array(
              0 => 'is_active',
             ),
             ));
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Team', array(
             'local' => 'team_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Asset', array(
             'local' => 'asset_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}