<?php

/**
 * BaseTournamentPhaseStrip
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $tournament_phase_strip_ext_id
 * @property integer $tournament_phase_id
 * @property string $name
 * @property string $description
 * @property integer $display_order
 * @property TournamentPhase $TournamentPhase
 * @property Doctrine_Collection $TournamentStandings
 * 
 * @method integer              getTournamentPhaseStripExtId()     Returns the current record's "tournament_phase_strip_ext_id" value
 * @method integer              getTournamentPhaseId()             Returns the current record's "tournament_phase_id" value
 * @method string               getName()                          Returns the current record's "name" value
 * @method string               getDescription()                   Returns the current record's "description" value
 * @method integer              getDisplayOrder()                  Returns the current record's "display_order" value
 * @method TournamentPhase      getTournamentPhase()               Returns the current record's "TournamentPhase" value
 * @method Doctrine_Collection  getTournamentStandings()           Returns the current record's "TournamentStandings" collection
 * @method TournamentPhaseStrip setTournamentPhaseStripExtId()     Sets the current record's "tournament_phase_strip_ext_id" value
 * @method TournamentPhaseStrip setTournamentPhaseId()             Sets the current record's "tournament_phase_id" value
 * @method TournamentPhaseStrip setName()                          Sets the current record's "name" value
 * @method TournamentPhaseStrip setDescription()                   Sets the current record's "description" value
 * @method TournamentPhaseStrip setDisplayOrder()                  Sets the current record's "display_order" value
 * @method TournamentPhaseStrip setTournamentPhase()               Sets the current record's "TournamentPhase" value
 * @method TournamentPhaseStrip setTournamentStandings()           Sets the current record's "TournamentStandings" collection
 * 
 * @package    futebol
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTournamentPhaseStrip extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tournament_phase_strip');
        $this->hasColumn('tournament_phase_strip_ext_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('tournament_phase_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('display_order', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TournamentPhase', array(
             'local' => 'tournament_phase_id',
             'foreign' => 'id'));

        $this->hasMany('TournamentStandings', array(
             'local' => 'id',
             'foreign' => 'tournament_phase_strip_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}