<?php

/**
 * BaseAsset
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $asset_type_id
 * @property integer $user_id
 * @property string $title
 * @property string $description
 * @property boolean $is_active
 * @property integer $views
 * @property boolean $ugc
 * @property timestamp $date_start
 * @property timestamp $date_end
 * @property AssetType $AssetType
 * @property sfGuardUser $sfGuardUser
 * @property Doctrine_Collection $RelatedAssets
 * @property Doctrine_Collection $Teams
 * @property Doctrine_Collection $Tournaments
 * @property Doctrine_Collection $Games
 * @property AssetContent $AssetContent
 * @property AssetImage $AssetImage
 * @property AssetVideo $AssetVideo
 * @property AssetAudio $AssetAudio
 * @property AssetFile $AssetFile
 * @property AssetImageGallery $AssetImageGallery
 * @property AssetAudioGallery $AssetAudioGallery
 * @property AssetVideoGallery $AssetVideoGallery
 * @property AssetQuestionnaire $AssetQuestionnaire
 * @property AssetQuestion $AssetQuestion
 * @property AssetAnswer $AssetAnswer
 * @property AssetVote $AssetVote
 * 
 * @method integer             getAssetTypeId()        Returns the current record's "asset_type_id" value
 * @method integer             getUserId()             Returns the current record's "user_id" value
 * @method string              getTitle()              Returns the current record's "title" value
 * @method string              getDescription()        Returns the current record's "description" value
 * @method boolean             getIsActive()           Returns the current record's "is_active" value
 * @method integer             getViews()              Returns the current record's "views" value
 * @method boolean             getUgc()                Returns the current record's "ugc" value
 * @method timestamp           getDateStart()          Returns the current record's "date_start" value
 * @method timestamp           getDateEnd()            Returns the current record's "date_end" value
 * @method AssetType           getAssetType()          Returns the current record's "AssetType" value
 * @method sfGuardUser         getSfGuardUser()        Returns the current record's "sfGuardUser" value
 * @method Doctrine_Collection getRelatedAssets()      Returns the current record's "RelatedAssets" collection
 * @method Doctrine_Collection getTeams()              Returns the current record's "Teams" collection
 * @method Doctrine_Collection getTournaments()        Returns the current record's "Tournaments" collection
 * @method Doctrine_Collection getGames()              Returns the current record's "Games" collection
 * @method AssetContent        getAssetContent()       Returns the current record's "AssetContent" value
 * @method AssetImage          getAssetImage()         Returns the current record's "AssetImage" value
 * @method AssetVideo          getAssetVideo()         Returns the current record's "AssetVideo" value
 * @method AssetAudio          getAssetAudio()         Returns the current record's "AssetAudio" value
 * @method AssetFile           getAssetFile()          Returns the current record's "AssetFile" value
 * @method AssetImageGallery   getAssetImageGallery()  Returns the current record's "AssetImageGallery" value
 * @method AssetAudioGallery   getAssetAudioGallery()  Returns the current record's "AssetAudioGallery" value
 * @method AssetVideoGallery   getAssetVideoGallery()  Returns the current record's "AssetVideoGallery" value
 * @method AssetQuestionnaire  getAssetQuestionnaire() Returns the current record's "AssetQuestionnaire" value
 * @method AssetQuestion       getAssetQuestion()      Returns the current record's "AssetQuestion" value
 * @method AssetAnswer         getAssetAnswer()        Returns the current record's "AssetAnswer" value
 * @method AssetVote           getAssetVote()          Returns the current record's "AssetVote" value
 * @method Asset               setAssetTypeId()        Sets the current record's "asset_type_id" value
 * @method Asset               setUserId()             Sets the current record's "user_id" value
 * @method Asset               setTitle()              Sets the current record's "title" value
 * @method Asset               setDescription()        Sets the current record's "description" value
 * @method Asset               setIsActive()           Sets the current record's "is_active" value
 * @method Asset               setViews()              Sets the current record's "views" value
 * @method Asset               setUgc()                Sets the current record's "ugc" value
 * @method Asset               setDateStart()          Sets the current record's "date_start" value
 * @method Asset               setDateEnd()            Sets the current record's "date_end" value
 * @method Asset               setAssetType()          Sets the current record's "AssetType" value
 * @method Asset               setSfGuardUser()        Sets the current record's "sfGuardUser" value
 * @method Asset               setRelatedAssets()      Sets the current record's "RelatedAssets" collection
 * @method Asset               setTeams()              Sets the current record's "Teams" collection
 * @method Asset               setTournaments()        Sets the current record's "Tournaments" collection
 * @method Asset               setGames()              Sets the current record's "Games" collection
 * @method Asset               setAssetContent()       Sets the current record's "AssetContent" value
 * @method Asset               setAssetImage()         Sets the current record's "AssetImage" value
 * @method Asset               setAssetVideo()         Sets the current record's "AssetVideo" value
 * @method Asset               setAssetAudio()         Sets the current record's "AssetAudio" value
 * @method Asset               setAssetFile()          Sets the current record's "AssetFile" value
 * @method Asset               setAssetImageGallery()  Sets the current record's "AssetImageGallery" value
 * @method Asset               setAssetAudioGallery()  Sets the current record's "AssetAudioGallery" value
 * @method Asset               setAssetVideoGallery()  Sets the current record's "AssetVideoGallery" value
 * @method Asset               setAssetQuestionnaire() Sets the current record's "AssetQuestionnaire" value
 * @method Asset               setAssetQuestion()      Sets the current record's "AssetQuestion" value
 * @method Asset               setAssetAnswer()        Sets the current record's "AssetAnswer" value
 * @method Asset               setAssetVote()          Sets the current record's "AssetVote" value
 * 
 * @package    futebol
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAsset extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('asset');
        $this->hasColumn('asset_type_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('views', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ugc', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('date_start', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('date_end', 'timestamp', null, array(
             'type' => 'timestamp',
             ));


        $this->index('is_active_idx', array(
             'fields' => 
             array(
              0 => 'is_active',
             ),
             ));
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AssetType', array(
             'local' => 'asset_type_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasMany('RelatedAsset as RelatedAssets', array(
             'local' => 'id',
             'foreign' => 'asset_id'));

        $this->hasMany('Team as Teams', array(
             'refClass' => 'TeamAsset',
             'local' => 'asset_id',
             'foreign' => 'team_id'));

        $this->hasMany('Tournament as Tournaments', array(
             'refClass' => 'TournamentAsset',
             'local' => 'asset_id',
             'foreign' => 'tournament_id'));

        $this->hasMany('Game as Games', array(
             'refClass' => 'GameAsset',
             'local' => 'asset_id',
             'foreign' => 'game_id'));

        $this->hasOne('AssetContent', array(
             'local' => 'id',
             'foreign' => 'asset_id'));

        $this->hasOne('AssetImage', array(
             'local' => 'id',
             'foreign' => 'asset_id'));

        $this->hasOne('AssetVideo', array(
             'local' => 'id',
             'foreign' => 'asset_id'));

        $this->hasOne('AssetAudio', array(
             'local' => 'id',
             'foreign' => 'asset_id'));

        $this->hasOne('AssetFile', array(
             'local' => 'id',
             'foreign' => 'asset_id'));

        $this->hasOne('AssetImageGallery', array(
             'local' => 'id',
             'foreign' => 'asset_id'));

        $this->hasOne('AssetAudioGallery', array(
             'local' => 'id',
             'foreign' => 'asset_id'));

        $this->hasOne('AssetVideoGallery', array(
             'local' => 'id',
             'foreign' => 'asset_id'));

        $this->hasOne('AssetQuestionnaire', array(
             'local' => 'id',
             'foreign' => 'asset_id'));

        $this->hasOne('AssetQuestion', array(
             'local' => 'id',
             'foreign' => 'asset_id'));

        $this->hasOne('AssetAnswer', array(
             'local' => 'id',
             'foreign' => 'asset_id'));

        $this->hasOne('AssetVote', array(
             'local' => 'id',
             'foreign' => 'asset_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable();
        $taggable0 = new Taggable();
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
        $this->actAs($taggable0);
    }
}