<?php

/**
 * BaseTournamentFeed
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $tournament_id
 * @property integer $feed_id
 * @property boolean $is_active
 * @property integer $display_order
 * @property Tournament $Tournament
 * @property Feed $Feed
 * 
 * @method integer        getTournamentId()  Returns the current record's "tournament_id" value
 * @method integer        getFeedId()        Returns the current record's "feed_id" value
 * @method boolean        getIsActive()      Returns the current record's "is_active" value
 * @method integer        getDisplayOrder()  Returns the current record's "display_order" value
 * @method Tournament     getTournament()    Returns the current record's "Tournament" value
 * @method Feed           getFeed()          Returns the current record's "Feed" value
 * @method TournamentFeed setTournamentId()  Sets the current record's "tournament_id" value
 * @method TournamentFeed setFeedId()        Sets the current record's "feed_id" value
 * @method TournamentFeed setIsActive()      Sets the current record's "is_active" value
 * @method TournamentFeed setDisplayOrder()  Sets the current record's "display_order" value
 * @method TournamentFeed setTournament()    Sets the current record's "Tournament" value
 * @method TournamentFeed setFeed()          Sets the current record's "Feed" value
 * 
 * @package    futebol
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTournamentFeed extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tournament_feed');
        $this->hasColumn('tournament_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('feed_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('display_order', 'integer', null, array(
             'type' => 'integer',
             ));


        $this->index('is_active_idx', array(
             'fields' => 
             array(
              0 => 'is_active',
             ),
             ));
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Tournament', array(
             'local' => 'tournament_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Feed', array(
             'local' => 'feed_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}