<?php

/**
 * BaseGameAsset
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $game_id
 * @property integer $asset_id
 * @property boolean $is_active
 * @property integer $display_order
 * @property Game $Tournament
 * @property Asset $Asset
 * @property Game $Game
 * 
 * @method integer   getGameId()        Returns the current record's "game_id" value
 * @method integer   getAssetId()       Returns the current record's "asset_id" value
 * @method boolean   getIsActive()      Returns the current record's "is_active" value
 * @method integer   getDisplayOrder()  Returns the current record's "display_order" value
 * @method Game      getTournament()    Returns the current record's "Tournament" value
 * @method Asset     getAsset()         Returns the current record's "Asset" value
 * @method Game      getGame()          Returns the current record's "Game" value
 * @method GameAsset setGameId()        Sets the current record's "game_id" value
 * @method GameAsset setAssetId()       Sets the current record's "asset_id" value
 * @method GameAsset setIsActive()      Sets the current record's "is_active" value
 * @method GameAsset setDisplayOrder()  Sets the current record's "display_order" value
 * @method GameAsset setTournament()    Sets the current record's "Tournament" value
 * @method GameAsset setAsset()         Sets the current record's "Asset" value
 * @method GameAsset setGame()          Sets the current record's "Game" value
 * 
 * @package    futebol
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGameAsset extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('game_asset');
        $this->hasColumn('game_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('asset_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('display_order', 'integer', null, array(
             'type' => 'integer',
             ));


        $this->index('is_active_idx', array(
             'fields' => 
             array(
              0 => 'is_active',
             ),
             ));
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Game as Tournament', array(
             'local' => 'game_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Asset', array(
             'local' => 'asset_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Game', array(
             'local' => 'game_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}