<?php

/**
 * BaseTournamentPhaseGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $tournament_phase_group_ext_id
 * @property integer $tournament_phase_id
 * @property string $name
 * @property string $description
 * @property string $round
 * @property integer $display_order
 * @property TournamentPhase $TournamentPhase
 * @property Doctrine_Collection $TournamentPhaseGroupTeams
 * 
 * @method integer              getTournamentPhaseGroupExtId()     Returns the current record's "tournament_phase_group_ext_id" value
 * @method integer              getTournamentPhaseId()             Returns the current record's "tournament_phase_id" value
 * @method string               getName()                          Returns the current record's "name" value
 * @method string               getDescription()                   Returns the current record's "description" value
 * @method string               getRound()                         Returns the current record's "round" value
 * @method integer              getDisplayOrder()                  Returns the current record's "display_order" value
 * @method TournamentPhase      getTournamentPhase()               Returns the current record's "TournamentPhase" value
 * @method Doctrine_Collection  getTournamentPhaseGroupTeams()     Returns the current record's "TournamentPhaseGroupTeams" collection
 * @method TournamentPhaseGroup setTournamentPhaseGroupExtId()     Sets the current record's "tournament_phase_group_ext_id" value
 * @method TournamentPhaseGroup setTournamentPhaseId()             Sets the current record's "tournament_phase_id" value
 * @method TournamentPhaseGroup setName()                          Sets the current record's "name" value
 * @method TournamentPhaseGroup setDescription()                   Sets the current record's "description" value
 * @method TournamentPhaseGroup setRound()                         Sets the current record's "round" value
 * @method TournamentPhaseGroup setDisplayOrder()                  Sets the current record's "display_order" value
 * @method TournamentPhaseGroup setTournamentPhase()               Sets the current record's "TournamentPhase" value
 * @method TournamentPhaseGroup setTournamentPhaseGroupTeams()     Sets the current record's "TournamentPhaseGroupTeams" collection
 * 
 * @package    futebol
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTournamentPhaseGroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tournament_phase_group');
        $this->hasColumn('tournament_phase_group_ext_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('tournament_phase_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('round', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('display_order', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TournamentPhase', array(
             'local' => 'tournament_phase_id',
             'foreign' => 'id'));

        $this->hasMany('TournamentPhaseGroupTeam as TournamentPhaseGroupTeams', array(
             'local' => 'id',
             'foreign' => 'tournament_phase_group_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}