<?php

/**
 * BaseTournamentPhaseGroupTeam
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $tournament_phase_group_team_ext_id
 * @property integer $tournament_phase_group_id
 * @property integer $team_id
 * @property string $label
 * @property integer $display_order
 * @property integer $rank
 * @property TournamentPhaseGroup $TournamentPhaseGroup
 * @property Team $Team
 * 
 * @method integer                  getTournamentPhaseGroupTeamExtId()      Returns the current record's "tournament_phase_group_team_ext_id" value
 * @method integer                  getTournamentPhaseGroupId()             Returns the current record's "tournament_phase_group_id" value
 * @method integer                  getTeamId()                             Returns the current record's "team_id" value
 * @method string                   getLabel()                              Returns the current record's "label" value
 * @method integer                  getDisplayOrder()                       Returns the current record's "display_order" value
 * @method integer                  getRank()                               Returns the current record's "rank" value
 * @method TournamentPhaseGroup     getTournamentPhaseGroup()               Returns the current record's "TournamentPhaseGroup" value
 * @method Team                     getTeam()                               Returns the current record's "Team" value
 * @method TournamentPhaseGroupTeam setTournamentPhaseGroupTeamExtId()      Sets the current record's "tournament_phase_group_team_ext_id" value
 * @method TournamentPhaseGroupTeam setTournamentPhaseGroupId()             Sets the current record's "tournament_phase_group_id" value
 * @method TournamentPhaseGroupTeam setTeamId()                             Sets the current record's "team_id" value
 * @method TournamentPhaseGroupTeam setLabel()                              Sets the current record's "label" value
 * @method TournamentPhaseGroupTeam setDisplayOrder()                       Sets the current record's "display_order" value
 * @method TournamentPhaseGroupTeam setRank()                               Sets the current record's "rank" value
 * @method TournamentPhaseGroupTeam setTournamentPhaseGroup()               Sets the current record's "TournamentPhaseGroup" value
 * @method TournamentPhaseGroupTeam setTeam()                               Sets the current record's "Team" value
 * 
 * @package    futebol
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTournamentPhaseGroupTeam extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tournament_phase_group_team');
        $this->hasColumn('tournament_phase_group_team_ext_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('tournament_phase_group_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('team_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('label', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('display_order', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('rank', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TournamentPhaseGroup', array(
             'local' => 'tournament_phase_group_id',
             'foreign' => 'id'));

        $this->hasOne('Team', array(
             'local' => 'team_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}