<?php

/**
 * BaseGameFeed
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $game_id
 * @property integer $feed_id
 * @property boolean $is_active
 * @property integer $display_order
 * @property Game $Game
 * @property Feed $Feed
 * 
 * @method integer  getGameId()        Returns the current record's "game_id" value
 * @method integer  getFeedId()        Returns the current record's "feed_id" value
 * @method boolean  getIsActive()      Returns the current record's "is_active" value
 * @method integer  getDisplayOrder()  Returns the current record's "display_order" value
 * @method Game     getGame()          Returns the current record's "Game" value
 * @method Feed     getFeed()          Returns the current record's "Feed" value
 * @method GameFeed setGameId()        Sets the current record's "game_id" value
 * @method GameFeed setFeedId()        Sets the current record's "feed_id" value
 * @method GameFeed setIsActive()      Sets the current record's "is_active" value
 * @method GameFeed setDisplayOrder()  Sets the current record's "display_order" value
 * @method GameFeed setGame()          Sets the current record's "Game" value
 * @method GameFeed setFeed()          Sets the current record's "Feed" value
 * 
 * @package    futebol
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGameFeed extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('game_feed');
        $this->hasColumn('game_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('feed_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('display_order', 'integer', null, array(
             'type' => 'integer',
             ));


        $this->index('is_active_idx', array(
             'fields' => 
             array(
              0 => 'is_active',
             ),
             ));
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Game', array(
             'local' => 'game_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Feed', array(
             'local' => 'feed_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}