<?php

/**
 * BaseTournament
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $tournament_ext_id
 * @property string $name
 * @property string $description
 * @property Doctrine_Collection $Feed
 * @property Doctrine_Collection $Feeds
 * @property Doctrine_Collection $TournamentEditions
 * @property Doctrine_Collection $TournamentStandings
 * @property Doctrine_Collection $Games
 * @property Doctrine_Collection $Asset
 * 
 * @method integer             getTournamentExtId()     Returns the current record's "tournament_ext_id" value
 * @method string              getName()                Returns the current record's "name" value
 * @method string              getDescription()         Returns the current record's "description" value
 * @method Doctrine_Collection getFeed()                Returns the current record's "Feed" collection
 * @method Doctrine_Collection getFeeds()               Returns the current record's "Feeds" collection
 * @method Doctrine_Collection getTournamentEditions()  Returns the current record's "TournamentEditions" collection
 * @method Doctrine_Collection getTournamentStandings() Returns the current record's "TournamentStandings" collection
 * @method Doctrine_Collection getGames()               Returns the current record's "Games" collection
 * @method Doctrine_Collection getAssets()              Returns the current record's "Assets" collection
 * @method Doctrine_Collection getAsset()               Returns the current record's "Asset" collection
 * @method Tournament          setTournamentExtId()     Sets the current record's "tournament_ext_id" value
 * @method Tournament          setName()                Sets the current record's "name" value
 * @method Tournament          setDescription()         Sets the current record's "description" value
 * @method Tournament          setFeed()                Sets the current record's "Feed" collection
 * @method Tournament          setFeeds()               Sets the current record's "Feeds" collection
 * @method Tournament          setTournamentEditions()  Sets the current record's "TournamentEditions" collection
 * @method Tournament          setTournamentStandings() Sets the current record's "TournamentStandings" collection
 * @method Tournament          setGames()               Sets the current record's "Games" collection
 * @method Tournament          setAssets()              Sets the current record's "Assets" collection
 * @method Tournament          setAsset()               Sets the current record's "Asset" collections
 * @property Doctrine_Collection $Asset
 * 
 * @method integer             getTournamentExtId()     Returns the current record's "tournament_ext_id" value
 * @method string              getName()                Returns the current record's "name" value
 * @method string              getDescription()         Returns the current record's "description" value
 * @method Doctrine_Collection getFeed()                Returns the current record's "Feed" collection
 * @method Doctrine_Collection getFeeds()               Returns the current record's "Feeds" collection
 * @method Doctrine_Collection getTournamentEditions()  Returns the current record's "TournamentEditions" collection
 * @method Doctrine_Collection getTournamentStandings() Returns the current record's "TournamentStandings" collection
 * @method Doctrine_Collection getGames()               Returns the current record's "Games" collection
 * @method Doctrine_Collection getAssets()              Returns the current record's "Assets" collection
 * @method Doctrine_Collection getAsset()               Returns the current record's "Asset" collection
 * @method Tournament          setTournamentExtId()     Sets the current record's "tournament_ext_id" value
 * @method Tournament          setName()                Sets the current record's "name" value
 * @method Tournament          setDescription()         Sets the current record's "description" value
 * @method Tournament          setFeed()                Sets the current record's "Feed" collection
 * @method Tournament          setFeeds()               Sets the current record's "Feeds" collection
 * @method Tournament          setTournamentEditions()  Sets the current record's "TournamentEditions" collection
 * @method Tournament          setTournamentStandings() Sets the current record's "TournamentStandings" collection
 * @method Tournament          setGames()               Sets the current record's "Games" collection
 * @method Tournament          setAssets()              Sets the current record's "Assets" collection
 * @method Tournament          setAsset()               Sets the current record's "Asset" collection
 * 
 * @package    futebol
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTournament extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tournament');
        $this->hasColumn('tournament_ext_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Feed', array(
             'refClass' => 'TournamentFeed',
             'local' => 'tournament_id',
             'foreign' => 'feed_id'));

        $this->hasMany('TournamentFeed as Feeds', array(
             'local' => 'id',
             'foreign' => 'tournament_id'));

        $this->hasMany('TournamentEdition as TournamentEditions', array(
             'local' => 'id',
             'foreign' => 'tournament_id'));

        $this->hasMany('TournamentStandings', array(
             'local' => 'id',
             'foreign' => 'tournament_id'));

        $this->hasMany('Game as Games', array(
             'local' => 'id',
             'foreign' => 'tournament_id'));

        $this->hasMany('TournamentAsset as Assets', array(
             'local' => 'id',
             'foreign' => 'tournament_id'));

        $this->hasMany('Asset', array(
             'refClass' => 'TournamentAsset',
             'local' => 'tournament_id',
             'foreign' => 'asset_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable();
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}