<?php

/**
 * BaseTournamentAsset
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $tournament_id
 * @property integer $asset_id
 * @property boolean $is_active
 * @property integer $display_order
 * @property Tournament $Tournament
 * @property Asset $Asset
 * 
 * @method integer         getTournamentId()  Returns the current record's "tournament_id" value
 * @method integer         getAssetId()       Returns the current record's "asset_id" value
 * @method boolean         getIsActive()      Returns the current record's "is_active" value
 * @method integer         getDisplayOrder()  Returns the current record's "display_order" value
 * @method Tournament      getTournament()    Returns the current record's "Tournament" value
 * @method Asset           getAsset()         Returns the current record's "Asset" value
 * @method TournamentAsset setTournamentId()  Sets the current record's "tournament_id" value
 * @method TournamentAsset setAssetId()       Sets the current record's "asset_id" value
 * @method TournamentAsset setIsActive()      Sets the current record's "is_active" value
 * @method TournamentAsset setDisplayOrder()  Sets the current record's "display_order" value
 * @method TournamentAsset setTournament()    Sets the current record's "Tournament" value
 * @method TournamentAsset setAsset()         Sets the current record's "Asset" value
 * 
 * @package    futebol
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTournamentAsset extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tournament_asset');
        $this->hasColumn('tournament_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('asset_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('display_order', 'integer', null, array(
             'type' => 'integer',
             ));


        $this->index('is_active_idx', array(
             'fields' => 
             array(
              0 => 'is_active',
             ),
             ));
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Tournament', array(
             'local' => 'tournament_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Asset', array(
             'local' => 'asset_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}