# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  stylesheets:    [core.css, /js/plupload/js/jquery.ui.plupload/css/jquery.ui.plupload.css, /js/plupload/js/jquery.plupload.queue/css/jquery.plupload.queue.css]
  javascripts:    [jquery-ui-1.8.16/js/jquery-1.6.2.min.js, jquery-ui-1.8.16/js/jquery-ui-1.8.16.custom.min.js, plupload/js/plupload.full.js, plupload/js/jquery.plupload.queue/jquery.plupload.queue.js, plupload/js/i18n/pt-br.js]
