# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values

all:

  melody:
    create_user: false
    redirect_register: @oauth_register
    redirect_error: @oauth_error

    facebook:
      key: XXX
      secret: XXX
      callback: @oauth_connect
      scope: [email]

    twitter:
      key: XXX
      secret: XXX
      api: YOUR_API_HERE
      callback: @oauth_connect
      scope: [email]

  sf_phpopenid_plugin:
    lib_path: %SF_ROOT_DIR%/lib/vendor/php-openid
    create_user: false
    redirect_register: @openid_register
