<?php

/**
 * IdentityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IdentityTable extends PluginIdentityTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object IdentityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Identity');
    }
}