<?php

/**
 * AssetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AssetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AssetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Asset');
    }
}