<?php

/**
 * GameFeedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GameFeedTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GameFeedTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GameFeed');
    }
}