<?php

/**
 * GameAssetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GameAssetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GameAssetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GameAsset');
    }
}