<?php

/**
 * StadiumTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StadiumTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StadiumTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Stadium');
    }
}