<?php

/**
 * TeamFeedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TeamFeedTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TeamFeedTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TeamFeed');
    }
}