<?php

/**
 * TeamAssetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TeamAssetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TeamAssetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TeamAsset');
    }
}