<?php

/**
 * TournamentStandingsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TournamentStandingsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TournamentStandingsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TournamentStandings');
    }
}