<?php

/**
 * TournamentFeedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TournamentFeedTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TournamentFeedTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TournamentFeed');
    }
}