<?php

/**
 * TournamentEditionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TournamentEditionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TournamentEditionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TournamentEdition');
    }
}