<?php

/**
 * TournamentPhaseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TournamentPhaseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TournamentPhaseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TournamentPhase');
    }
}