<?php

/**
 * TournamentPhaseStripTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TournamentPhaseStripTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TournamentPhaseStripTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TournamentPhaseStrip');
    }
}