<?php

/**
 * TournamentPhaseGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TournamentPhaseGroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TournamentPhaseGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TournamentPhaseGroup');
    }
}