<?php

/**
 * TournamentAssetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TournamentAssetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TournamentAssetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TournamentAsset');
    }
}