<?php

/**
 * TournamentPhaseGroupTeamTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TournamentPhaseGroupTeamTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TournamentPhaseGroupTeamTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TournamentPhaseGroupTeam');
    }
}