generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Feed
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          feed
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      filter:
        display: [slug, name, description, type, url, site_name, site_url, is_active, tournaments_list, teams_list]
      form:    ~
      edit:    ~
      new:     ~
