<?php

/**
 * BaseIdentity
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $user_id
 * @property string $identifier
 * @property string $status
 * @property sfGuardUser $User
 * 
 * @method integer     getId()         Returns the current record's "id" value
 * @method string      getName()       Returns the current record's "name" value
 * @method integer     getUserId()     Returns the current record's "user_id" value
 * @method string      getIdentifier() Returns the current record's "identifier" value
 * @method string      getStatus()     Returns the current record's "status" value
 * @method sfGuardUser getUser()       Returns the current record's "User" value
 * @method Identity    setId()         Sets the current record's "id" value
 * @method Identity    setName()       Sets the current record's "name" value
 * @method Identity    setUserId()     Sets the current record's "user_id" value
 * @method Identity    setIdentifier() Sets the current record's "identifier" value
 * @method Identity    setStatus()     Sets the current record's "status" value
 * @method Identity    setUser()       Sets the current record's "User" value
 * 
 * @package    futebol
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseIdentity extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('identity');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 127, array(
             'type' => 'string',
             'length' => 127,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('identifier', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('status', 'string', 127, array(
             'type' => 'string',
             'length' => 127,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}