generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Game
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          game_tournament_games
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title:   Tournament games
        display: [Tournament, date_start, date, time, round, Stadium, home_team_name, home_team_score, away_team_score, away_team_name, created_at, updated_at]
        object_actions:
          synchronize:  ~
          details:      ~
          _edit:        ~
          _delete:      ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
