detect_relations: true

Tournament:
  options:
    collate: utf8_unicode_ci
    charset: utf8
  actAs: { Timestampable: ~, Sluggable: fields: [name] canUpdate: true unique: true, }
  columns:
    tournament_ext_id:  { type: integer }
    name:               { type: string(255), notnull: true }
    description:        { type: string(255), notnull: true }

TournamentEdition:
  options:
    collate: utf8_unicode_ci
    charset: utf8
  actAs: { Timestampable: ~, Sluggable: fields: [name] canUpdate: true unique: true, }
  columns:
    tournament_edition_ext_id:  { type: integer }
    tournament_id:              { type: integer }
    name:                       { type: string(255), notnull: true }
    description:                { type: string(255), notnull: true }
    rules:                      { type: text }
    location:                   { type: string(255), notnull: true }
    date_start:                 { type: timestamp, notnull: true }
    date_end:                   { type: timestamp, notnull: true }
  relations:
    Tournament: { local: tournament_id, foreign: id, foreignAlias: TournamentEditions }

TournamentPhase:
  options:
    collate: utf8_unicode_ci
    charset: utf8
  actAs: { Timestampable: ~, Sluggable: fields: [name] canUpdate: true unique: true, }
  columns:
    tournament_phase_ext_id:  { type: integer }
    name:                     { type: string(255), notnull: true }
    description:              { type: string(255), notnull: true }
    display_order:            { type: integer }
    location:                 { type: string(255), notnull: true }
    type:                     { type: string(255), notnull: true }
    classification_type:      { type: string(255), notnull: true }
    is_active:                { type: boolean, notnull: true, default: 0 }
  indexes:
    is_active_idx:
      fields: [is_active]

TournamentPhaseStrip:
  options:
    collate: utf8_unicode_ci
    charset: utf8
  actAs: { Timestampable: ~ }
  columns:
    tournament_phase_strip_ext_id:  { type: integer }
    tournament_phase_id:            { type: integer }
    name:                           { type: string(255), notnull: true }
    description:                    { type: string(255), notnull: true }
    display_order:                  { type: integer }
  relations:
    TournamentPhase: { local: tournament_phase_id, foreign: id, foreignAlias: TournamentPhaseStrips }

TournamentPhaseGroup:
  options:
    collate: utf8_unicode_ci
    charset: utf8
  actAs: { Timestampable: ~ }
  columns:
    tournament_phase_group_ext_id:  { type: integer }
    tournament_phase_id:            { type: integer }
    name:                           { type: string(255), notnull: true }
    description:                    { type: string(255), notnull: true }
    round:                          { type: string(255), notnull: true }
    display_order:                  { type: integer }
  relations:
    TournamentPhase: { local: tournament_phase_id, foreign: id, foreignAlias: TournamentPhaseStrips }

TournamentPhaseGroupTeam:
  options:
    collate: utf8_unicode_ci
    charset: utf8
  actAs: { Timestampable: ~ }
  columns:
    tournament_phase_group_team_ext_id:   { type: integer }
    tournament_phase_group_id:            { type: integer }
    team_id:                              { type: integer }
    label:                                { type: string(255) }
    display_order:                        { type: integer }
    rank:                                 { type: integer }
  relations:
    TournamentPhaseGroup: { local: tournament_phase_group_id, foreign: id, foreignAlias: TournamentPhaseGroupTeams }
    Team: { local: team_id, foreign: id, foreignAlias: TournamentPhaseGroupTeams }

TournamentStandings:
  options:
    collate: utf8_unicode_ci
    charset: utf8
  actAs: { Timestampable: ~ }
  columns:
    team_id:                    { type: integer }
    tournament_phase_strip_id:  { type: integer }
    rank:                       { type: float }
    defeats:                    { type: integer }
    draws:                      { type: integer }
    wins:                       { type: integer }
    points:                     { type: float }
    score_for:                  { type: integer }
    score_against:              { type: integer }
    score_difference:           { type: integer }
    games:                      { type: integer }
    variation:                  { type: integer }
    display_order:              { type: string(255) }

Team:
  options:
    collate: utf8_unicode_ci
    charset: utf8
  actAs: { Timestampable: ~, Sluggable: fields: [name] canUpdate: true unique: true, }
  columns:
    team_ext_id:     { type: integer }
    official_name:      { type: string(255), notnull: true }
    name:               { type: string(255), notnull: true }
    nickname:           { type: string(255), notnull: true }
    logo:               { type: string(255), notnull: true }
    initials:           { type: string(255), notnull: true }
    description:        { type: string(255), notnull: true }

Stadium:
  options:
    collate: utf8_unicode_ci
    charset: utf8
  actAs: { Timestampable: ~, Sluggable: fields: [name] canUpdate: true unique: true, }
  columns:
    stadium_ext_id:     { type: integer }
    official_name:      { type: string(255), notnull: true }
    name:               { type: string(255), notnull: true }
    nickname:           { type: string(255), notnull: true }
    capacity:           { type: string(255), notnull: true }
    address:            { type: string(255), notnull: true }
    inauguration:       { type: string(255), notnull: true }
    location:           { type: string(255), notnull: true }
    geo_location:       { type: string(255), notnull: true }

Game:
  options:
    collate: utf8_unicode_ci
    charset: utf8
  actAs: { Timestampable: ~, }
  columns:
    tournament_id:            { type: integer }
    game_ext_id:              { type: integer }
    date_start:               { type: timestamp, notnull: true }
    date:                     { type: string(255), notnull: true }
    time:                     { type: string(255), notnull: true }
    round:                    { type: string(255), notnull: true }
    home_team_id:             { type: integer }
    home_team_ext_id:         { type: integer }
    home_team_logo:           { type: string(255), notnull: true }
    home_team_name:           { type: string(255), notnull: true }
    home_team_initials:       { type: string(255), notnull: true }
    home_team_slug:           { type: string(255), notnull: true }
    home_team_score:          { type: integer }
    home_team_penalty_score:  { type: integer }
    away_team_id:             { type: integer }
    away_team_ext_id:         { type: integer }
    away_team_logo:           { type: string(255), notnull: true }
    away_team_name:           { type: string(255), notnull: true }
    away_team_initials:       { type: string(255), notnull: true }
    away_team_slug:           { type: string(255), notnull: true }
    away_team_score:          { type: integer }
    away_team_penalty_score:  { type: integer }
    stadium_name:             { type: string(255), notnull: true }
    stadium_id:               { type: integer }
    stadium_ext_id:           { type: integer }
    url:                      { type: string(255), notnull: true }
  relations:
    Tournament: { local: tournament_id, foreign: id, class: Tournament, foreignAlias: Games }
    HomeTeam: { local: home_team_id, foreign: id, class: Team, foreignAlias: HomeGames }
    AwayTeam: { local: away_team_id, foreign: id, class: Team, foreignAlias: AwayGames } 
