generator:
  class: sfDoctrineGenerator
  param:
    model_class:           TournamentEdition
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tournament_edition
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title:   Tournament editions
        display: [=name, description, slug, created_at, updated_at]
        object_actions:
          games:     ~
          _edit:        ~
          _delete:      ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
